### ISSUE TITLE
Strange delay randomly

### ISSUE THREAD

**Issue by antoniomechas** [watab0shi/ofxUST#3]
Hello,
I'm using your addon in two different installations... working like a charm!!
But... in one of them, which is running 3 different Apps, there is a random delay in the scan. It seems to be related to the FPS the app is running... I'm not able to find what causes this delay. Running on windows 10
Any thoughts?
Thanks!
Antonio.

**Comment by watab0shi** [comment]
@antoniomechas 
Hello Antonio,
Thank you for using my addon.
I was aware of the windows delay, but had not fixed it.
Thanks to your Issue for giving me the opportunity to fix it.
Finally, I solved it by extending ofThread.
You can pull the latest commits and should replace startMeasurement / stopMeasurement with start / stop.
Hope it works!

**Comment by antoniomechas** [comment]
Hello watab0shi...
Many thanks for your quick response... I was also thinking about using ofThread, but it is really wonderful you already did it.
I'll test it next week and see if everything works fine!
Thanks for your help!! I really apreciate it!
Antonio.
